//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRE_Auftragseingabe {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings_UbootClass : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_UbootClass defaultInstance = ((Settings_UbootClass)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_UbootClass())));
        
        public static Settings_UbootClass Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\Pruefstrassen\\FRE-Autragseingabe\\FRE-Auftragseingabe\\FRE-Auftragseingabe\\bin\\D" +
            "ebug\\net7.0-windows\\")]
        public string pathIcon {
            get {
                return ((string)(this["pathIcon"]));
            }
            set {
                this["pathIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YelSub.ico")]
        public string fileicon {
            get {
                return ((string)(this["fileicon"]));
            }
            set {
                this["fileicon"] = value;
            }
        }
    }
}
